
name: Deployment-Develop

on: 
  push:
    branches:    
      - develop 

jobs:
  deploy-storybook:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 
      uses: actions/setup-node@v1
      with:
        node-version: 14

    - name: setup
      run: |
        npm config set //registry.npmjs.org/:_authToken=$NPM_TOKEN
        npm config set "@fortawesome:registry" https://npm.fontawesome.com/
        npm config set //npm.fontawesome.com/:_authToken=$FA_TOKEN
        npm ci
      env: 
        NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        FA_TOKEN: ${{ secrets.FA_TOKEN }}

    - name: npm install
      run: |
        npm ci
    
    - name: Prepare Artifact
      run: |
        npm run build-storybook
        rm -rf .git
        git clone https://github.com/Faxi-Kinto/web-react-deployment-wrapper deploy
        cd deploy
        rm -rf .git
        mv ../storybook-static build
        git init
        git config --global user.email "me@jonjoe.io"
        git config --global user.name "Jonjoe Whitfield"
        git add .
        git commit -m "deployment"
        git remote add heroku https://heroku:1e7cfe01-5561-45e8-aee9-44d21efbafcb@git.heroku.com/faxi-cl-storybook-develop.git
    
    - name: Deploy to Heroku
      run: |
        cd deploy
        git push heroku HEAD:master -f
    
