
name: Deployment-Develop

on: 
  push:
    branches:    
      - develop 

jobs:
  run:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 
      uses: actions/setup-node@v1
      with:
        node-version: 14

    - name: base-setup
      run: |
        rm -rf ./.git
        rm -rf ./.gitignore
        git config --global user.email "me@jonjoe.io"
        git config --global user.name "Jonjoe Whitfield"
        npm config set //registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}
        npm config set "@fortawesome:registry" https://npm.fontawesome.com/
        npm config set //npm.fontawesome.com/:_authToken=${{ secrets.FA_TOKEN }}
        npm ci
     
    - name: setup-storybook
      run: |
        git clone https://github.com/Faxi-Kinto/web-react-deployment-wrapper storybook
        cd ./storybook 
        rm -rf ./.git
        git init
        git remote add heroku https://heroku:${{ secrets.HEROKU_TOKEN }}@git.heroku.com/faxi-cl-storybook-develop.git
    
    - name: build-storybook
      run: |
        npm run build-storybook
        mv ./storybook-static ./storybook/build

    - name: deploy-storybook
      run: |
        cd storybook
        git add .
        git commit -m "deployment"
        git push heroku HEAD:master -f
    
    
